version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm i
      - npm run build
      - aws s3 rm s3://conference-list.com/css
      - aws s3 rm s3://conference-list.com/js
      - aws s3 rm s3://conference-list.com/*.ico
      - aws s3 rm s3://conference-list.com/*.html
      - aws s3 cp --recursive dist/ s3://conference-list.com/
